# Generated by Django 5.1.7 on 2025-03-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishes', '0002_wish_edited_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
